### ISSUE TITLE
Not supported on Android TVs

### ISSUE THREAD

**Issue by lbridgman** [x-falcon/Virtual-Hosts#16]
There are a bunch of us over on [Reddit](https://www.reddit.com/r/LazyMan/comments/81s0g1/android_guide_no_root_needed/?sort=new) trying to get this app to function on Android TVs.  We can sideload the APK but get a "You don't have an app that can do this" message when we try to select a hosts file.

**Comment by x-falcon** [comment]
This is because，select hosts file need to call system document manager which provide by the system app DocumentUi.apk.
But most TV deleted this app for some reason.
And this Document Management Function been   provided from android 4.4, but many tv use base on android 4.2.

The advantage of using this feature is that the APP do not need to apply for file read and write permissions.

If your tv based on 4.4 and above, you can install the app DocumentsUI.apk manually.

**Comment by lbridgman** [comment]
Thanks!  I installed the APK successfully, rebooted my TV and launched the Virtual Hosts app again but got the same results (You don't have an app that can do this).  I'm running on Marshmallow, I'll see if there's maybe a more appropriate APK out there..

**Comment by x-falcon** [comment]
Suddenly discovered that this error message is not send by the app, the app will send message "System File Browser Not Find" if the DocumentUI.apk does not exist. so the error message may be from the system.  and  your  tv system is deeply customized, in that case, it may  be not  compatible.
If convenient, please provide specific device information.
In the future, I will use my free time to add built-in file manager to app and get files over the network so that can compatible with more devices. 

tips: the version 1.6.4 has some bug, please use the new version 1.6.7 https://github.com/x-falcon/Virtual-Hosts/releases/download/1.6.7/app-Github-release.apk

**Comment by 10pmStalker** [comment]
That's great falcon. Thanks for all your work. Hoping to see a version that will fix the error.

**Comment by lbridgman** [comment]
@x-falcon thank you for the update.  On my side I can say that I am using a Sony XBR-55X850D on Android 6.0.1 Marshmallow.  Much appreciated!

**Comment by acleee** [comment]
@x-falcon do you think it would be possible to tell the app to use any file manager the user would have installed? I know some apps would offer me the option to use solid explorer, ES file explorer, etc. instead of the default `com.android.documentsui` app.

**Comment by albaphysic** [comment]
I have the same issue on my Xiaomi MiBox running 6.0.1

I tried sideloading the DocumentsUI.apk linked by @x-falcon (I believe it's the 5.1.1 version) as well as [this one I found on apk mirror for 6.0.1](https://www.apkmirror.com/apk/xiaomi-inc/documents-xiaomi/documents-xiaomi-6-0-1-release/documents-6-0-1-2-android-apk-download/)

I was able to install the former but it didn't work (tried rebooting). The 6.0.1 one didn't want to install for me.

A built-in file manager would be much appreciated :)

**Comment by x-falcon** [comment]
In fact , support url will be  better,
but busy , busy , busy

**Comment by krotki1** [comment]
Any way to make it work on Sony android tv ?

**Comment by sansillusion** [comment]
Still no way to make it work on android tv ? I would really like to load a hosts file

**Comment by albaphysic** [comment]
@sansillusion Works on Android TV, just some things are not possible without a mouse connected (eg. the switch to turn it on needs a swipe up motion).

An alternative to a mouse would be sideloading CetusPlay Remote apk which turns your phone into a virtual mouse. https://www.reddit.com/r/LazyMan/wiki/android

@x-falcon Would be cool if you could make it remote friendly

**Comment by sansillusion** [comment]
It does not work I cant select a file with it I get a message that there is no app to do this, and when I install com.android.documentsui, com.android.documentsui just crashes not possible to select a file

**Comment by albaphysic** [comment]
Press _and hold_ on the "Select hosts file" button and you'll get a menu like this: 
![image](https://user-images.githubusercontent.com/26522326/52892861-ef3b3100-3196-11e9-813a-9f7e06ae66f2.png)

**Comment by sansillusion** [comment]
Thanks found it now I need to find how to click with the mouse mode on cetus play, so many stick in my wheels damn it's not easy.

**Comment by sansillusion** [comment]
Somehow got it to work after some restarting etc... the mouse pointer was showing but for some reason it would not send clicks. after a few reboot and tries I got it to work !!! YAY !!! Now on to find out how to save streams from kodi and I am all set ! Thanks for the app !
