### ISSUE TITLE
New features : multiple host list and whitelist app

### ISSUE THREAD

**Issue by motfis** [x-falcon/Virtual-Hosts#23]
Is it possible to add more features : 
1. To be able loading several host files
2. To whitelist app from host filtering

**Comment by x-falcon** [comment]
The first function has been implemented .
You  can long click the select host file button to find and test it. This
feature is currently in beta

The second, I will think about it.
Maybe I think it is not worth it.
Because in fact all traffic is whitelisted, except for dns traffic.

2018年7月5日星期四，motfis <notifications@github.com> 写道：

**Comment by motfis** [comment]
I don't understand. I long press the re-select host file. I can put url and download it. But I didn't find option to select (for example) two host files.
Also there is option from local and from internet, which I don't understand how to use it.
For #2, for example for adblocking, i want some apps to be bypassed.

**Comment by x-falcon** [comment]
1,Currently only supports one online hosts file.
After click download, you can select from internet ,then back to the main interface ,click the switch, your hosts file from net will effective.
If you want use local hosts file, just select from local , then back to the main interface, restart the  switch.

2,for the whitelist , If there is free time, I will consider adding this feature

**Comment by kitkatloyalist** [comment]
i would never want any third party ads whitelisted.  That entirely defeats the priciple: privacy.
