### ISSUE TITLE
VPN Is Bypassed On Android Pie

### ISSUE THREAD

**Issue by AndyWhittaker** [x-falcon/Virtual-Hosts#28]
This is to reopen bug #27 

My OnePlus6 has been running virtual host for several months now with no issue. So much so, I bought the app within Google Play Store. However, I have recently upgraded my OS to Android Pie and it no longer works. If I, for example, browse to [The Register](https://theregister.co.uk) it contains adverts once more. Other sites are the same.

**Comment by x-falcon** [comment]
Can you take a screenshot or take a video? I need to restore the scene.Because I have no equipment based Android 9.

**Comment by x-falcon** [comment]
@AndyWhittaker This problem seems to be caused by chrome.
 please test this ,
 https://www.androidsage.com/2018/01/25/how-to-fix-adhell-2-not-working-chrome/

Enter the URL “chrome://flags”, without quotes, into the address bar.
Search "dns"
Set the “Async DNS” option to “Disabled” and close the tab.

**Comment by pplante** [comment]
That doesn't resolve the issue. I see Google Ads in other apps that used to be blocked.

**Comment by kitkatloyalist** [comment]
Which flavor of vpn?

**Comment by highKo84** [comment]
Same problem with my Huawei Mate 10 pro after updating to Android 9 pie.
Disabling Async DNS in chrome also didn't help
